from __future__ import annotations

import ast  # noqa: F401
import copy  # noqa: F401
import json  # noqa: F401
import logging  # noqa: F401
import time  # noqa: F401
import warnings  # noqa: F401
from dataclasses import dataclass  # noqa: F401
from pathlib import Path  # noqa: F401
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple  # noqa: F401

import pandas as pd  # noqa: F401
import torch  # noqa: F401

from exact.utils.data import read_yaml  # noqa: F401
from exact.utils.formatting import format_duration as _format_duration  # noqa: F401

from .export import _write_json


def _write_notebook(output_dir: Path) -> Path:
    notebook_path = output_dir / "user_study_analysis.ipynb"
    analysis_dir = str(output_dir.resolve())
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# EXACT User Study Review and Failure Analysis\n",
                    "\n",
                    "This notebook is generated from the artifacts produced by `exact-user-study`.\n",
                    "It is designed for two separate review tasks:\n",
                    "\n",
                    "1. **User-study review**: inspect the shortlist and final selected 20 sources that will be shown to users.\n",
                    "2. **Failure analysis**: inspect where the ranking loses the gold target and which signals appear to drive those failures.\n",
                    "\n",
                    "The notebook keeps these tasks separate so case selection and model-error analysis remain easy to reason about.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## What This Notebook Loads\n",
                    "\n",
                    "The notebook works only from the saved analysis artifacts. It does **not** rerun alignment or rationale generation.\n",
                    "\n",
                    "Key files:\n",
                    "- `eligible_panels.csv`: source panels that passed the hard completeness checks.\n",
                    "- `study_shortlist.csv`: auto-ranked shortlist before manual review.\n",
                    "- `study_selection_review.csv`: editable review sheet used to freeze the final 20 panels.\n",
                    "- `study_selected_records_with_rationales.json`: the final 20 x 5 selected pair records, including rationales when available.\n",
                    "- `study_mapping.json`: the exported user-study payload.\n",
                    "- `failure_taxonomy.csv`: one row per source for ranking-failure analysis.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "from pathlib import Path\n",
                    "import json\n",
                    "from collections import Counter\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "\n",
                    "try:\n",
                    "    from IPython.display import display\n",
                    "except ImportError:\n",
                    "    display = print\n",
                    "\n",
                    f'ANALYSIS_DIR = Path(r"{analysis_dir}")\n',
                    "PAIR_METRICS_PATH = ANALYSIS_DIR / 'pair_metrics.csv'\n",
                    "eligible = pd.read_csv(ANALYSIS_DIR / 'eligible_panels.csv')\n",
                    "source_panels = pd.read_csv(ANALYSIS_DIR / 'source_panels.csv')\n",
                    "shortlist = pd.read_csv(ANALYSIS_DIR / 'study_shortlist.csv')\n",
                    "review = pd.read_csv(ANALYSIS_DIR / 'study_selection_review.csv')\n",
                    "failure = pd.read_csv(ANALYSIS_DIR / 'failure_taxonomy.csv')\n",
                    "study_mapping = json.loads((ANALYSIS_DIR / 'study_mapping.json').read_text(encoding='utf-8'))\n",
                    "selected_records_path = ANALYSIS_DIR / 'study_selected_records_with_rationales.json'\n",
                    "selected_records = json.loads(selected_records_path.read_text(encoding='utf-8')) if selected_records_path.exists() else []\n",
                    "\n",
                    "def _bridge_counts(row):\n",
                    "    provenance = row.get('cross_side_provenance') or {}\n",
                    "    lexical = len(list(provenance.get('lexical') or []))\n",
                    "    hierarchy = sum(len(list(links or [])) for links in dict(provenance.get('hierarchy') or {}).values())\n",
                    "    similarity = len(list(provenance.get('similarity') or []))\n",
                    "    attributes = dict(provenance.get('attributes') or {})\n",
                    "    attribute = len(list(attributes.get('source') or [])) + len(list(attributes.get('target') or []))\n",
                    "    difference = dict(provenance.get('difference') or {})\n",
                    "    contrast = len(list(difference.get('source') or [])) + len(list(difference.get('target') or []))\n",
                    "    return {\n",
                    "        'bridge_total_count': lexical + hierarchy + similarity + attribute + contrast,\n",
                    "        'bridge_support_count': lexical + hierarchy + similarity + attribute,\n",
                    "        'bridge_contrast_count': contrast,\n",
                    "        'has_nonlexical_bridge': int((hierarchy + similarity + attribute + contrast) > 0),\n",
                    "    }\n",
                    "\n",
                    "selected_panel_rows = []\n",
                    "for row in selected_records:\n",
                    "    meta = row.get('study_metadata') or {}\n",
                    "    labels = row.get('selected_labels') or {}\n",
                    "    prediction = row.get('prediction') or {}\n",
                    "    importances = row.get('importances') or {}\n",
                    "    confidences = row.get('confidences') or {}\n",
                    "    bridges = _bridge_counts(row)\n",
                    "    selected_panel_rows.append({\n",
                    "        'source_iri': meta.get('source_iri'),\n",
                    "        'rank': meta.get('rank'),\n",
                    "        'gold_rank': meta.get('gold_rank'),\n",
                    "        'ground_truth': meta.get('ground_truth'),\n",
                    "        'source_label': labels.get('source'),\n",
                    "        'target_label': labels.get('target'),\n",
                    "        'target_iri': row.get('tgt_iri'),\n",
                    "        'score': confidences.get('S_final'),\n",
                    "        'I_label': importances.get('I_label'),\n",
                    "        'I_struct': importances.get('I_struct'),\n",
                    "        'I_llm': importances.get('I_llm'),\n",
                    "        'has_pair_brief': bool(row.get('llm_pair_brief')),\n",
                    "        'has_rationale': bool(prediction.get('llm_rationale')),\n",
                    "        'bridge_total_count': bridges['bridge_total_count'],\n",
                    "        'bridge_support_count': bridges['bridge_support_count'],\n",
                    "        'bridge_contrast_count': bridges['bridge_contrast_count'],\n",
                    "        'has_nonlexical_bridge': bridges['has_nonlexical_bridge'],\n",
                    "    })\n",
                    "selected_panels = pd.DataFrame(selected_panel_rows)\n",
                    "\n",
                    "selected_sources = (\n",
                    "    selected_panels[['source_iri', 'source_label', 'gold_rank']]\n",
                    "    .drop_duplicates()\n",
                    "    .sort_values(['gold_rank', 'source_iri'])\n",
                    "    .reset_index(drop=True)\n",
                    ")\n",
                    "\n",
                    "artifact_summary = pd.DataFrame([\n",
                    "    {'artifact': 'eligible_panels.csv', 'exists': (ANALYSIS_DIR / 'eligible_panels.csv').exists(), 'rows': len(eligible)},\n",
                    "    {'artifact': 'study_shortlist.csv', 'exists': (ANALYSIS_DIR / 'study_shortlist.csv').exists(), 'rows': len(shortlist)},\n",
                    "    {'artifact': 'study_selection_review.csv', 'exists': (ANALYSIS_DIR / 'study_selection_review.csv').exists(), 'rows': len(review)},\n",
                    "    {'artifact': 'study_selected_records_with_rationales.json', 'exists': selected_records_path.exists(), 'rows': len(selected_records)},\n",
                    "    {'artifact': 'study_mapping.json', 'exists': (ANALYSIS_DIR / 'study_mapping.json').exists(), 'rows': len(study_mapping.get('pairs', []))},\n",
                    "    {'artifact': 'failure_taxonomy.csv', 'exists': (ANALYSIS_DIR / 'failure_taxonomy.csv').exists(), 'rows': len(failure)},\n",
                    "])\n",
                    "display(artifact_summary)\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## User Study\n",
                    "\n",
                    "This section focuses on whether the selected cases are suitable for human review.\n",
                    "The goal here is not to analyze ranking failures yet, but to verify that the user-study set is balanced, complete, and explanation-rich.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Selection Pipeline\n",
                    "\n",
                    "At a high level, the selection pipeline first removes panels that would be confusing or unusable for a study, and only then tries to rank the remaining panels by quality.\n",
                    "\n",
                    "In other words, the pipeline uses two layers:\n",
                    "- **Hard filters**: conditions that must hold for a panel to even be considered.\n",
                    "- **Soft ranking heuristics**: signals used to sort the surviving panels inside each gold-rank bucket.\n",
                    "\n",
                    "The analysis script applies the following steps:\n",
                    "\n",
                    "1. Read the score-sorted local ranking file and keep the top `k` candidates per source.\n",
                    "2. Exclude source panels with missing full explanation records among the displayed candidates. This is a usability filter: if a user will see five candidates, all five must have a proper explanation payload.\n",
                    "3. Keep only sources whose gold target rank is within the displayed review band. For a top-5 user study, the gold target must actually appear in the five candidates shown to the participant.\n",
                    "4. Auto-rank eligible panels inside each gold-rank bucket using pair-brief completeness, structural coverage, mean structural importance, evidence volume, and ambiguity. This does **not** guarantee semantic quality, but it is a pragmatic way to favor cases that are more reviewable and better supported.\n",
                    "5. Build a shortlist per bucket and then freeze a final set with exactly `per_rank` sources per bucket so the study is balanced across ranks 1 to 5.\n",
                    "\n",
                    "The next cells let you inspect those stages directly.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### How to Read the Eligibility Metrics\n",
                    "\n",
                    "The first summary table is meant to answer a simple question: *do we have enough usable source panels in each gold-rank bucket, and are those panels rich enough to support a meaningful study?*\n",
                    "\n",
                    "The columns mean:\n",
                    "- `eligible_count`: how many source panels survived the hard filters in that gold-rank bucket.\n",
                    "- `mean_I_struct`: average structural importance across candidate panels in the bucket. Higher values mean the non-lexical evidence is actually influencing the score rather than being merely present.\n",
                    "- `mean_evidence_volume`: average number of evidence items carried by the panel, using hierarchy, difference, and attribute evidence. Higher values usually mean more material for explanation, although very large values can also mean the panel is noisy.\n",
                    "- `pair_brief_complete_rate`: fraction of panels in the bucket where all displayed candidates already have a pair brief. A high value is good because it means the panel is closer to being directly reviewable.\n",
                    "- `structural_coverage_mean`: average number of structural channel families represented in the panel. In practice this summarizes whether the panel relies on only one kind of non-lexical evidence or several complementary kinds.\n",
                    "- `mean_bridge_total_count`: average number of cross-side links present in the saved explanations. Higher values usually mean the panel has more explicit grounding between source-side and target-side evidence, rather than two disconnected context islands.\n",
                    "- `nonlexical_bridge_rate`: fraction of panels in the bucket that contain at least one non-lexical bridge. This is a quick proxy for whether the explanation graph can visually connect both sides using ontology evidence instead of only the lexical source-to-target edge.\n",
                    "\n",
                    "There is no single 'perfect' number here. The main use of this table is comparative: one bucket is more comfortable to sample from when it has enough eligible panels and those panels are reasonably rich in evidence.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "eligibility_overview = (\n",
                    "    eligible.groupby('gold_rank')\n",
                    "    .agg(\n",
                    "        eligible_count=('src_iri', 'size'),\n",
                    "        mean_I_struct=('mean_I_struct', 'mean'),\n",
                    "        mean_evidence_volume=('mean_evidence_volume', 'mean'),\n",
                    "        pair_brief_complete_rate=('pair_brief_complete', 'mean'),\n",
                    "        structural_coverage_mean=('panel_structural_coverage', 'mean'),\n",
                    "        mean_bridge_total_count=('mean_bridge_total_count', 'mean'),\n",
                    "        nonlexical_bridge_rate=('panel_has_nonlexical_bridge', 'mean'),\n",
                    "    )\n",
                    "    .reset_index()\n",
                    ")\n",
                    "display(eligibility_overview)\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "fig, ax = plt.subplots(figsize=(8, 4))\n",
                    "eligibility_overview.plot.bar(x='gold_rank', y='eligible_count', ax=ax, legend=False, color='#4C78A8')\n",
                    "ax.set_title('Eligible source panels by gold rank bucket')\n",
                    "ax.set_xlabel('Gold rank bucket')\n",
                    "ax.set_ylabel('Eligible panels')\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Shortlist Review\n",
                    "\n",
                    "The shortlist is the automatic pool from which the final balanced 20 are chosen.\n",
                    "This is the right place to inspect whether the heuristic ranking is surfacing evidence-rich and explanation-rich cases.\n",
                    "\n",
                    "Use the summary first, then inspect per-rank buckets with the helper table below.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Heuristic Used to Rank the Shortlist\n",
                    "\n",
                    "The shortlist ranking is deliberately heuristic rather than learned. The goal is not to predict correctness again, but to prefer panels that are easier for a human to validate.\n",
                    "\n",
                    "In plain terms, the ranking prefers panels that:\n",
                    "- already have all pair briefs available,\n",
                    "- show several kinds of structural evidence rather than only one,\n",
                    "- give structural evidence non-trivial weight in the final score,\n",
                    "- contain enough evidence to be informative,\n",
                    "- are not completely trivial but also not so ambiguous that they become confusing,\n",
                    "- and, as a weak bonus, include similarity evidence when it exists.\n",
                    "\n",
                    "This is why the shortlist should be read as a **review aid**, not as a statement that the top auto-ranked panel is objectively the 'best' scientific example. It is the best example under the current operational goal: explainability and study usability.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### How to Read the Shortlist Metrics\n",
                    "\n",
                    "The shortlist tables expose the signals that drive the automatic ranking. The most important columns are:\n",
                    "- `pair_brief_count`: how many of the displayed candidates already have pair briefs. Higher is better for reviewability.\n",
                    "- `panel_structural_coverage`: how many structural channel groups are represented in the panel. Higher means the user is less likely to see a one-dimensional explanation.\n",
                    "- `mean_I_struct`: average importance of structural evidence across the panel. Higher means the explanation is not purely lexical.\n",
                    "- `mean_evidence_volume`: average amount of structural evidence in the panel. Higher generally means richer context, but if this is high while `mean_I_struct` stays low, the evidence may be present but not actually influential.\n",
                    "- `mean_ambiguity`: average ambiguity over the panel. The heuristic prefers moderate ambiguity because extremely easy cases may not be informative for a study, while extremely ambiguous cases may be frustrating for participants.\n",
                    "- `mean_bridge_total_count`: average number of bridge edges in the panel. Higher values usually mean the graph has more explicit cross-side grounding to show users.\n",
                    "- `panel_has_nonlexical_bridge`: whether at least one candidate in the panel has a non-lexical bridge. This matters because it tells you whether the graph can connect both sides through more than the label-match edge.\n",
                    "- `recommended_keep`: whether the automatic heuristic would keep this source if no manual review were applied.\n",
                    "\n",
                    "A useful practical rule is: prefer panels where the evidence is both **present** and **doing work**. That usually means looking for a sensible combination of `panel_structural_coverage`, `mean_evidence_volume`, and `mean_I_struct`, rather than optimizing a single column in isolation.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "shortlist_overview = (\n",
                    "    shortlist.groupby('gold_rank')\n",
                    "    .agg(\n",
                    "        shortlist_count=('src_iri', 'size'),\n",
                    "        recommended_keeps=('recommended_keep', 'sum'),\n",
                    "        mean_I_struct=('mean_I_struct', 'mean'),\n",
                    "        mean_evidence_volume=('mean_evidence_volume', 'mean'),\n",
                    "        mean_ambiguity=('mean_ambiguity', 'mean'),\n",
                    "        structural_coverage_mean=('panel_structural_coverage', 'mean'),\n",
                    "        mean_bridge_total_count=('mean_bridge_total_count', 'mean'),\n",
                    "        nonlexical_bridge_rate=('panel_has_nonlexical_bridge', 'mean'),\n",
                    "    )\n",
                    "    .reset_index()\n",
                    ")\n",
                    "display(shortlist_overview)\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "review_columns = [\n",
                    "    'gold_rank', 'auto_rank_within_bucket', 'src_iri', 'source_label',\n",
                    "    'gold_tgt_label', 'pair_brief_count', 'panel_structural_coverage',\n",
                    "    'mean_I_struct', 'mean_evidence_volume', 'mean_ambiguity',\n",
                    "    'mean_bridge_total_count', 'panel_has_nonlexical_bridge',\n",
                    "    'recommended_keep', 'keep', 'drop_reason', 'review_note'\n",
                    "]\n",
                    "display(review[review_columns].sort_values(['gold_rank', 'auto_rank_within_bucket']).head(20))\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def review_bucket(rank: int):\n",
                    "    cols = [\n",
                    "        'auto_rank_within_bucket', 'src_iri', 'source_label', 'gold_tgt_label',\n",
                    "        'pair_brief_count', 'panel_structural_coverage', 'mean_I_struct',\n",
                    "        'mean_evidence_volume', 'mean_ambiguity', 'mean_bridge_total_count',\n",
                    "        'panel_has_nonlexical_bridge', 'recommended_keep',\n",
                    "        'keep', 'drop_reason', 'review_note'\n",
                    "    ]\n",
                    "    bucket = review.loc[review['gold_rank'] == rank, cols].sort_values('auto_rank_within_bucket')\n",
                    "    return bucket.reset_index(drop=True)\n",
                    "\n",
                    "review_bucket(1)\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Final Selected Set\n",
                    "\n",
                    "The final study set should contain exactly 20 sources and exactly 5 displayed candidates per source.\n",
                    "These cells verify that the final selection is balanced by gold rank and that the selected panels contain the expected explanation material.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### How to Read the Final-Set Metrics\n",
                    "\n",
                    "The final-set summary is less about ranking quality and more about *study readiness*.\n",
                    "\n",
                    "The main columns are:\n",
                    "- `selected_sources`: number of unique sources selected in the bucket. This should match the intended balance, typically 4 per rank.\n",
                    "- `candidate_rows`: number of candidate records represented in that bucket. With top-5 panels, this should be `selected_sources * 5`.\n",
                    "- `rationale_rate`: fraction of displayed candidates that already have a rationale. A high value matters because the user-facing material is more complete.\n",
                    "- `pair_brief_rate`: fraction of displayed candidates that have pair briefs. This is a direct proxy for whether the explanatory package is complete.\n",
                    "- `mean_I_label`, `mean_I_struct`, `mean_I_llm`: average top-level contributions in the final selected panels. These are useful for checking whether the study set is overly dominated by one signal family.\n",
                    "- `mean_bridge_total_count`: average number of bridges per displayed candidate. Higher values generally mean more explicit cross-side grounding.\n",
                    "- `nonlexical_bridge_rate`: fraction of displayed candidates that contain at least one non-lexical bridge. This is a good sanity check for whether the final study set really showcases the pair-adaptive evidence instead of only lexical links.\n",
                    "- `mean_bridge_support_count` vs `mean_bridge_contrast_count`: rough split between bridges that connect supporting evidence and bridges that express one-sided contrast. A useful study set usually contains some of both, but not only contrast.\n",
                    "\n",
                    "A balanced user study usually benefits from variation. If the final set is almost entirely lexical or almost entirely structural, participants may get a narrow picture of how the system behaves.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "selected_sources.groupby('gold_rank').size().rename('selected_source_count')\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "selected_panel_summary = (\n",
                    "    selected_panels.groupby('gold_rank')\n",
                    "    .agg(\n",
                    "        selected_sources=('source_iri', 'nunique'),\n",
                    "        candidate_rows=('target_iri', 'size'),\n",
                    "        rationale_rate=('has_rationale', 'mean'),\n",
                    "        pair_brief_rate=('has_pair_brief', 'mean'),\n",
                    "        mean_I_label=('I_label', 'mean'),\n",
                    "        mean_I_struct=('I_struct', 'mean'),\n",
                    "        mean_I_llm=('I_llm', 'mean'),\n",
                    "        mean_bridge_total_count=('bridge_total_count', 'mean'),\n",
                    "        mean_bridge_support_count=('bridge_support_count', 'mean'),\n",
                    "        mean_bridge_contrast_count=('bridge_contrast_count', 'mean'),\n",
                    "        nonlexical_bridge_rate=('has_nonlexical_bridge', 'mean'),\n",
                    "    )\n",
                    "    .reset_index()\n",
                    ")\n",
                    "display(selected_panel_summary)\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(selected_sources)\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Selected Case Drilldown\n",
                    "\n",
                    "Use the helper below to inspect any selected source panel in detail.\n",
                    "It prints the five ranked candidates, their top-level scores and importances, and whether pair briefs and rationales are present.\n",
                    "\n",
                    "When reading the printed output, a useful mental model is:\n",
                    "- `score`, `s_label`, and `S_struct` tell you how the system arrived at the ranking.\n",
                    "- `I_label`, `I_struct`, and `I_llm` tell you which top-level signal families actually mattered.\n",
                    "- the evidence counts tell you whether the explanation is rich because there is real contextual support, or thin because the case relies mostly on labels.\n",
                    "- the bridge counts tell you whether the source and target sides are explicitly connected in the displayed graph, and whether those links are mostly support links or contrast links.\n",
                    "\n",
                    "This is the best place in the notebook to decide whether a source panel 'feels right' for a participant-facing study.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def _record_channel_counts(row):\n",
                    "    ctx = row.get('context_triples') or {}\n",
                    "    attrs = row.get('attributes') or {}\n",
                    "    hier_count = 0\n",
                    "    for side in ('source', 'target'):\n",
                    "        hier_payload = ctx.get(f'hierarchy_{side}') or {}\n",
                    "        for triples in hier_payload.values():\n",
                    "            hier_count += len(triples or [])\n",
                    "    sim_count = len(ctx.get('similarity_source') or []) + len(ctx.get('similarity_target') or [])\n",
                    "    diff_count = len(ctx.get('difference_source') or []) + len(ctx.get('difference_target') or [])\n",
                    "    attr_count = len(attrs.get('source') or []) + len(attrs.get('target') or [])\n",
                    "    return hier_count, sim_count, diff_count, attr_count\n",
                    "\n",
                    "def _record_bridge_counts(row):\n",
                    "    bridges = _bridge_counts(row)\n",
                    "    return bridges['bridge_total_count'], bridges['bridge_support_count'], bridges['bridge_contrast_count'], bridges['has_nonlexical_bridge']\n",
                    "\n",
                    "def show_selected_source(source_iri: str):\n",
                    "    rows = [row for row in selected_records if (row.get('study_metadata') or {}).get('source_iri') == source_iri]\n",
                    "    rows = sorted(rows, key=lambda row: (row.get('study_metadata') or {}).get('rank', 999))\n",
                    "    if not rows:\n",
                    "        print(f'No selected rows found for {source_iri}')\n",
                    "        return\n",
                    "    for row in rows:\n",
                    "        labels = row.get('selected_labels') or {}\n",
                    "        meta = row.get('study_metadata') or {}\n",
                    "        prediction = row.get('prediction') or {}\n",
                    "        importances = row.get('importances') or {}\n",
                    "        confidences = row.get('confidences') or {}\n",
                    "        hier_count, sim_count, diff_count, attr_count = _record_channel_counts(row)\n",
                    "        bridge_total, bridge_support, bridge_contrast, has_nonlex_bridge = _record_bridge_counts(row)\n",
                    "        print(f\"Rank {meta.get('rank')} | GT={meta.get('ground_truth')} | target={labels.get('target')}\")\n",
                    "        print(f\"  score={confidences.get('S_final')} s_label={confidences.get('s_label')} S_struct={confidences.get('S_struct')} p_llm={confidences.get('p_llm')}\")\n",
                    "        print(f\"  I_label={importances.get('I_label')} I_struct={importances.get('I_struct')} I_llm={importances.get('I_llm')}\")\n",
                    '        print(f"  evidence counts: hierarchy={hier_count} similarity={sim_count} difference={diff_count} attributes={attr_count}")\n',
                    '        print(f"  bridge counts: total={bridge_total} support={bridge_support} contrast={bridge_contrast} nonlexical_bridge={bool(has_nonlex_bridge)}")\n',
                    "        print(f\"  brief={bool(row.get('llm_pair_brief'))} rationale={bool(prediction.get('llm_rationale'))}\")\n",
                    "        print('  Pair brief:')\n",
                    "        print(row.get('llm_pair_brief', ''))\n",
                    "        print('  Rationale:')\n",
                    "        print(prediction.get('llm_rationale', ''))\n",
                    "        print('-' * 100)\n",
                    "\n",
                    "show_selected_source(selected_sources.iloc[0]['source_iri']) if not selected_sources.empty else None\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Failure Analysis\n",
                    "\n",
                    "This section focuses on ranking failures.\n",
                    "Each row in `failure_taxonomy.csv` compares the gold target with the top-1 distractor for one source and assigns a primary failure category.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Failure Taxonomy\n",
                    "\n",
                    "The failure taxonomy is a structured attempt to turn a raw ranking miss into a more interpretable explanation of *why* the gold target lost.\n",
                    "It is intentionally simple and rule-based. The goal is not to prove causality, but to sort errors into categories that are useful for diagnosis.\n",
                    "\n",
                    "Interpret the primary categories as follows:\n",
                    "\n",
                    "- `missing_panel_record`: the displayed panel was incomplete because at least one top-k candidate lacked a full explanation record.\n",
                    "- `gold_below_top5`: the gold target fell below the review band.\n",
                    "- `near_tie`: gold and top-1 are very close in final score.\n",
                    "- `gold_structurally_better_but_loses`: structural evidence supports the gold target, but the distractor still wins the final score.\n",
                    "- `top1_structurally_better`: the distractor has a clear structural advantage.\n",
                    "- `lexical_overweight`: lexical advantage appears to dominate while structural evidence is not clearly against the distractor.\n",
                    "- `evidence_sparse_other`: fallback bucket when none of the more specific rules fire.\n",
                    "\n",
                    "The ordering matters. For example, `near_tie` is checked before several other categories, because a tiny score difference is often the most important fact about the case even if other signals also differ.\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### How to Read the Failure Metrics\n",
                    "\n",
                    "Most failure-analysis columns are written as **gold minus top-1 distractor**.\n",
                    "That sign convention is important:\n",
                    "- a **positive** delta means the gold target has more of that property,\n",
                    "- a **negative** delta means the top-1 distractor has more of it.\n",
                    "\n",
                    "The most useful fields are:\n",
                    "- `score_gap`: `top1_score - gold_score`. A small positive value means a near miss; a large value means the distractor won comfortably.\n",
                    "- `delta_s_label`: lexical advantage of gold over top-1. Negative values mean the distractor looked lexically better.\n",
                    "- `delta_S_struct`: structural advantage of gold over top-1. Positive values mean the context supported gold more strongly.\n",
                    "- `delta_I_label` and `delta_I_struct`: differences in how much lexical vs structural evidence actually mattered in the final decision.\n",
                    "- `delta_bridge_total_count`: difference in explicit cross-side grounding between gold and top-1. Positive values mean the gold explanation exposes more bridge structure.\n",
                    "- `delta_bridge_support_count` and `delta_bridge_contrast_count`: split the bridge comparison into supporting links versus contrast links.\n",
                    "- `delta_U` and `delta_U_dis`: differences in uncertainty and disagreement. These are mainly useful as contextual cues, not as standalone failure explanations.\n",
                    "- `nonlex_sparse_*`: whether the case had weak non-lexical support relative to the run. These flags help distinguish genuine structural conflict from simple lack of evidence.\n",
                    "- `gold_has_nonlexical_bridge` and `top1_has_nonlexical_bridge`: whether each side of the comparison was backed by at least one non-lexical cross-side link. These help separate 'ungrounded' misses from grounded-but-conflicting ones.\n",
                    "\n",
                    "A simple reading strategy is:\n",
                    "1. Look at `score_gap` to judge whether the miss is mild or severe.\n",
                    "2. Compare `delta_s_label` and `delta_S_struct` to see whether lexical and structural evidence point in the same direction.\n",
                    "3. Use the bridge deltas and sparsity flags to decide whether the case is a real disagreement, a weakly grounded case, or simply an evidence-poor example.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "failure['primary_failure_category'].value_counts().rename_axis('category').reset_index(name='count')\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "failure['primary_failure_category'].value_counts().plot(kind='bar', figsize=(10, 4), title='Failure categories')\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "failure_overview = pd.DataFrame([\n",
                    "    {'metric': 'sources analysed', 'value': len(failure)},\n",
                    "    {'metric': 'panel complete rate', 'value': failure['panel_complete'].mean()},\n",
                    "    {'metric': 'llm active on top1 rate', 'value': failure['llm_active_top1'].mean()},\n",
                    "    {'metric': 'llm active on gold rate', 'value': failure['llm_active_gold'].mean()},\n",
                    "    {'metric': 'nonlex sparse top1 rate', 'value': failure['nonlex_sparse_top1'].mean()},\n",
                    "    {'metric': 'nonlex sparse gold rate', 'value': failure['nonlex_sparse_gold'].mean()},\n",
                    "    {'metric': 'top1 nonlexical bridge rate', 'value': failure['top1_has_nonlexical_bridge'].mean()},\n",
                    "    {'metric': 'gold nonlexical bridge rate', 'value': failure['gold_has_nonlexical_bridge'].mean()},\n",
                    "])\n",
                    "display(failure_overview)\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "bridge_failure_summary = (\n",
                    "    failure.groupby('primary_failure_category')\n",
                    "    .agg(\n",
                    "        count=('src_iri', 'size'),\n",
                    "        mean_score_gap=('score_gap', 'mean'),\n",
                    "        mean_delta_bridge_total=('delta_bridge_total_count', 'mean'),\n",
                    "        mean_delta_bridge_support=('delta_bridge_support_count', 'mean'),\n",
                    "        mean_delta_bridge_contrast=('delta_bridge_contrast_count', 'mean'),\n",
                    "        gold_nonlexical_bridge_rate=('gold_has_nonlexical_bridge', 'mean'),\n",
                    "        top1_nonlexical_bridge_rate=('top1_has_nonlexical_bridge', 'mean'),\n",
                    "    )\n",
                    "    .sort_values('count', ascending=False)\n",
                    "    .reset_index()\n",
                    ")\n",
                    "display(bridge_failure_summary)\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "ax = failure.plot.scatter(\n",
                    "    x='delta_s_label',\n",
                    "    y='delta_S_struct',\n",
                    "    c=failure['primary_failure_category'].astype('category').cat.codes,\n",
                    "    colormap='tab10',\n",
                    "    figsize=(7, 5),\n",
                    "    title='Gold minus top-1: lexical vs structural deltas',\n",
                    ")\n",
                    "ax.axhline(0.0, color='black', linewidth=1)\n",
                    "ax.axvline(0.0, color='black', linewidth=1)\n",
                    "ax.set_xlabel('delta_s_label (gold - top1)')\n",
                    "ax.set_ylabel('delta_S_struct (gold - top1)')\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### How to Read the Scatter Plot\n",
                    "\n",
                    "The scatter plot compares lexical and structural deltas at the same time.\n",
                    "\n",
                    "A rough quadrant interpretation is:\n",
                    "- **Upper right**: gold is stronger both lexically and structurally. If such cases still fail, something unusual is happening downstream.\n",
                    "- **Lower left**: the distractor is stronger on both signals. These are usually straightforward hard negatives from the system's perspective.\n",
                    "- **Upper left**: gold is structurally stronger but lexically weaker. These are often the most interesting cases because they expose tension between lexical and contextual evidence.\n",
                    "- **Lower right**: gold is lexically stronger but structurally weaker. These are also informative because they show where structure pushes against the lexical signal.\n",
                    "\n",
                    "After reading the quadrants, it is useful to compare them with the bridge summary above. That tells you whether a disagreement case is at least well grounded by explicit cross-side links, or whether the failure is happening in a graph that never became meaningfully connected in the first place.\n",
                    "\n",
                    "In practice, the most diagnostically useful cases are often the ones near the axes or in the disagreement quadrants, not necessarily the ones with the largest absolute values.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "top5_errors = failure[failure['gold_rank'].between(2, 5)]\n",
                    "below_top5 = failure[failure['primary_failure_category'] == 'gold_below_top5']\n",
                    "plt.figure(figsize=(8, 4))\n",
                    "plt.hist(top5_errors['score_gap'].dropna(), bins=20, alpha=0.6, label='rank 2-5 misses')\n",
                    "if not below_top5.empty:\n",
                    "    plt.hist(below_top5['score_gap'].dropna(), bins=20, alpha=0.6, label='gold below top 5')\n",
                    "plt.legend()\n",
                    "plt.title('Score-gap histograms')\n",
                    "plt.xlabel('top1 score - gold score')\n",
                    "plt.ylabel('number of sources')\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "worst_losses = failure.sort_values('score_gap', ascending=False)[[\n",
                    "    'src_iri', 'source_label', 'gold_rank', 'primary_failure_category',\n",
                    "    'score_gap', 'delta_s_label', 'delta_S_struct', 'delta_U_dis'\n",
                    "]].head(20)\n",
                    "display(worst_losses)\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Reading the Worst-Loss Table\n",
                    "\n",
                    "The worst-loss table is a prioritization tool.\n",
                    "It surfaces the sources where the gold target lost by the largest final-score margin, together with the key lexical and structural deltas.\n",
                    "\n",
                    "This is useful when you want to inspect only a handful of failures manually. A practical way to use it is to pick:\n",
                    "- one or two large-margin failures from each major category,\n",
                    "- one or two near ties,\n",
                    "- and one or two disagreement cases where lexical and structural evidence pull in opposite directions.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def show_failure_case(source_iri: str):\n",
                    "    row = failure.loc[failure['src_iri'] == source_iri]\n",
                    "    if row.empty:\n",
                    "        print(f'No failure row found for {source_iri}')\n",
                    "        return\n",
                    "    row = row.iloc[0]\n",
                    "    print('Source:', row['source_label'])\n",
                    "    print('Primary category:', row['primary_failure_category'])\n",
                    "    print('Gold target:', row['gold_tgt_label'])\n",
                    "    print('Top-1 target:', row['top1_tgt_label'])\n",
                    "    print('Gold rank:', row['gold_rank'])\n",
                    "    print('Score gap:', row['score_gap'])\n",
                    "    print('delta_s_label:', row['delta_s_label'])\n",
                    "    print('delta_S_struct:', row['delta_S_struct'])\n",
                    "    print('delta_I_label:', row['delta_I_label'])\n",
                    "    print('delta_I_struct:', row['delta_I_struct'])\n",
                    "    print('delta_bridge_total_count:', row['delta_bridge_total_count'])\n",
                    "    print('delta_bridge_support_count:', row['delta_bridge_support_count'])\n",
                    "    print('delta_bridge_contrast_count:', row['delta_bridge_contrast_count'])\n",
                    "    print('delta_U:', row['delta_U'])\n",
                    "    print('delta_U_dis:', row['delta_U_dis'])\n",
                    "    print('Flags:')\n",
                    "    for col in [\n",
                    "        'llm_active_top1', 'llm_active_gold', 'nonlex_sparse_top1',\n",
                    "        'nonlex_sparse_gold', 'similarity_present_in_panel',\n",
                    "        'top1_has_nonlexical_bridge', 'gold_has_nonlexical_bridge',\n",
                    "        'high_disagreement_gold', 'high_disagreement_top1'\n",
                    "    ]:\n",
                    "        print(f'  {col}: {row[col]}')\n",
                    "    print('\\nSelected-panel drilldown, if this source is part of the study set:')\n",
                    "    show_selected_source(source_iri)\n",
                    "\n",
                    "show_failure_case(failure.iloc[0]['src_iri']) if not failure.empty else None\n",
                ],
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Recommended Review Workflow\n",
                    "\n",
                    "A practical workflow is:\n",
                    "\n",
                    "1. Inspect the **eligible panel counts** by gold rank to make sure each bucket is sampleable.\n",
                    "2. Review the **shortlist** with `review_bucket(rank)` and decide whether the recommended picks are acceptable from a human-study perspective.\n",
                    "3. Verify the **final selected set** is balanced and explanation-rich, rather than dominated by one signal family.\n",
                    "4. Use `show_selected_source(...)` to inspect any source that might enter the user study. This is the qualitative sanity-check step.\n",
                    "5. Move to the **failure analysis** section and use `show_failure_case(...)` on representative failures from each category.\n",
                    "6. Only after both reviews are complete should the study set be treated as final. The point is not just to get 20 examples, but to get 20 examples that are both analytically informative and participant-friendly.\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    _write_json(notebook_path, notebook)
    return notebook_path
