
# System Parameters

## Verbosity level of the logs.
logging_level: INFO

# Seed for reproducibility.
seed: 42

## Used cached files to skip computations if available.
use_file_cache: False

# Evaluation Parameters

## Number of top-k predictions to be considered for evaluation.
k: [1, 5, 10]

# Alignment Parameters

alignment_params:
  ### ONLY USED FOR GLOBAL ALIGNMENT TASKS ###

  ## Threshold to be used to filter predictions.
  ## If Null, final alignment will not be filtered by score.
  threshold: 0.7 # 0.7

  ## Cardinality to be used to filter predictions.
  ## If Null, final alignment will not be filtered by cardinality.
  ## Only used in full alignment tasks.
  cardinality: null # 1

dataset_params:

  ## Number of workers to be used to load the data. If null, the all available cores will be used.
  num_workers: null

  pre_filtering: True # If True, matcha scores will be used to filter easy mappings in the inference set.

  sanity_check: True # If True, the data will be checked for sanity before training.
  
  # Context Tabular Dataset Configs [Optional] Only used if model is EncoderClassifier
  n_hops: 1
  context_method: bfs
  best_path_src_method: dp
  context_hop_penalty: 0.1
  context_token_ratio: 1.3
  context_safety: 0.8
  verbaliser_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  gen_max_new_tokens: 32768 # Max number of new tokens to be generated by the model for the context.
  batch_size: 32
  do_sample: False # If True sampling will be used to generate the context.
  temperature: null # Temperature to be used in sampling. If >1, the model will be more creative.
  top_k: null # Top-k to be used in sampling. If >0, the model will only sample from the top-k most probable tokens.
  top_p: null # Top-p to be used in sampling. If >0, the model will only sample from the top-p most probable tokens.
  delimiter: ""
  exclude_missing_dr: False
  cache_chunk_size: 100000 # Number of rows to be cached in memory before writing to disk.
  gen_max_length: null
  encoding_max_length: 256 # Max length of the input sequence to the model.
  summariser_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  max_verb_gen_retries: 1
  smallest_batch_first: False # If True, the smallest batch will be processed first.
  only_taxonomy: False # If True, only the taxonomy will be used to generate the context.
  sanity_check_n_samples: 5 # Number of samples to be used in the sanity check.

inference_params:
  batch_size: 1 # 1, 32
  num_workers: 0
  log_every: 10
  mixed_precision: True
  
model:
  name: EncoderClassifier
  params:
    encoder_name: sentence-transformers/all-MiniLM-L6-v2
    pooling: sum # sum, cls, max, sum_max, cls_mean, attentive (only for supervised settings)
    fusion: weighted_cosine
    label_pooling: max_pair # max_pair, concat
    ctx_pooling: max_pair # max_pair, concat
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.05