
# System Parameters

## Verbosity level of the logs.
logging_level: INFO

# Seed for reproducibility.
seed: 42

## Used cached files to skip computations if available.
use_file_cache: False

## Use the last checkpoint to continue training
use_last_checkpoint: False

## If True, the training will be skipped if a checkpoint is found.

skip_training_if_checkpoint: False

# Evaluation Parameters

## Number of top-k predictions to be considered for evaluation.
k: [1, 5, 10]

# Alignment Parameters

alignment_params:
  ### ONLY USED FOR GLOBAL ALIGNMENT TASKS ###

  ## Threshold to be used to filter predictions.
  ## If Null, final alignment will not be filtered by score.
  threshold: 0.7 # 0.7

  ## Cardinality to be used to filter predictions.
  ## If Null, final alignment will not be filtered by cardinality.
  ## Only used in full alignment tasks.
  cardinality: null # 1

matcha_params:
  ## JAVA Heap Size
  max_heap: 64G
  ## Filter to generate candidates for global alignment.
  threshold: 0.9 # 0.7, 0.8, 0.9
  ## Matchers ro be used to calculate the similarity between the candidates.
  matchers: [LM, BKM, SM, WM, LLM]
  # Cardinality of negatives in the training set
  negcardinality: null # If null or not delclared, the cardinality will be calculated based on the positive set cardinality.
  # Filter to generate negatives in the training set
  negthreshold: 0.1 #0.4, 0.5, 0.6
  # Samplers to be used to generate negatives in the training set
  samplers: rand # all, rand, diff
  # If True, a reference set will be generated for the training set if no reference set is provided.
  generate_reference: True
  # Minimim threshold to be used to filter the hard positives
  min_threshold_hard_positives: 0.85
  # Minimim threshold to be used to filter the soft positives
  min_threshold_soft_positives: 0.65
  # Number of hard positives to be used in generated the training set
  hard_positives: 1
  # Number of soft positives to be used in generated the training set
  soft_positives: 0.5
  # If matcha scores should be calculated. Serves to speed up the process if not needed. Warning: If False, the scores will not be available and can break the pipeline.
  calculate_scores: True

## Whether to plot the distribution of the similarities in the negative set.
plot_negatives:
  enabled: True
  figsize: [8, 5]
  kde: True
  bins: 20
  color: blue
  alpha: 0.6
  dpi: 300
  grid: True

dataset_params:
  ## Validation set to be used to stop training, and in training guidance.
  ## If Null or not declared, no validation set will be used.
  validation_set: 0.1

  ## Number of workers to be used to load the data. If null, the all available cores will be used.
  num_workers: null

  pre_filtering: True # If True, matcha scores will be used to filter easy mappings in the inference set.
  pre_filtering_threshold: 0.85 # Threshold to be used to filter easy mappings in the inference set.
  
  ## Prompt Dataset Configs [Optional] Only used if model is prompt based
  ## Should should be list of params of size n (equal for all lists so that it can behabe like an array)
  ## If only one value is given, a single prompt will be used per source-target pair
  ## If n values are given, n prompts will be used per source-target pair and will be agregated following the agrgg param
  example: [False] # True, False
  positive_examples: [1] #1, 3, 5
  negative_examples: [1] #1, 3, 5
  task_context: [True] #
  separator: [comma] # comma, paranthesis
  comparison_type: [synonyms] # synonyms, equivalent, a_match
  label_cardinality: [1] #  3, 5, 100
  context_type : [superclasses] # superclasses, subclasses, top_superclass
  context_cardinality: [1] # 3, 5, 100
  context_semantics: [a_part_of] # a_part_of, a_kind_of, a_type_of, a_subclass_of, with_subclass, with_part, with_type, with_kind
  likelihood: [float] # float, cat

  # Context Tabular Dataset Configs [Optional] Only used if model is EncoderClassifier
  n_hops: 1
  context_method: bfs
  best_path_src_method: dp
  context_hop_penalty: 0.1
  context_token_ratio: 1.3
  context_safety: 0.8
  verbaliser_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  gen_max_new_tokens: 32768 # Max number of new tokens to be generated by the model for the context.
  batch_size: 32
  do_sample: False # If True sampling will be used to generate the context.
  temperature: null # Temperature to be used in sampling. If >1, the model will be more creative.
  top_k: null # Top-k to be used in sampling. If >0, the model will only sample from the top-k most probable tokens.
  top_p: null # Top-p to be used in sampling. If >0, the model will only sample from the top-p most probable tokens.
  num_beams: 1 # If >1 beam search will be used to generate the context.
  early_stopping: False # If True, the generation will stop when all beams reach the end token.
  aggregation_strategy: join # join, summarise
  delimiter: \n
  exclude_missing_dr: False
  cache_chunk_size: 100000 # Number of rows to be cached in memory before writing to disk.
  gen_max_length: null
  encoding_max_length: 256 # Max length of the input sequence to the model.
  summariser_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  max_verb_gen_retries: 1
  smallest_batch_first: False # If True, the smallest batch will be processed first.
  batch_length_sort_mode: max # max, sum
  only_taxonomy: False # If True, only the taxonomy will be used to generate the context.

training_params:
  epochs: 10 # 50
  batch_size: 1 # 1, 32
  num_workers: 0
  shuffle: True
  val_every: 1
  save_interval: 5
  log_every: 10
  ## Not used in for MLP models
  gradient_accumulation_steps: 1
  mixed_precision: True
  warmup_percent: 0.1
  
stopper:
  name: StableLossStopping
  params:
    patience: 5 # 5, 10
    min_delta: 1e-4

# model:
#   name: MlpClassifier
#   params:
#     layers: [128, 256, 128]

# model:
#   name: PromptClassifier
#   params:
#     model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
#     use_critic: True
#     critic_weight: 0.5
#     critic_uncertainty: True
#     max_length: 50
#     aggregation_strategy: 'mean' # mean, max, min
#     use_lora: True
#     lora_r: 16
#     lora_alpha: 32
#     lora_dropout: 0.05

model:
  name: EncoderClassifier
  params:
    encoder_name: sentence-transformers/all-MiniLM-L6-v2
    pooling: sum # sum, cls, max, sum_max, cls_mean, attentive (only for supervised settings)
    use_lora: True
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    use_classifier: False # If True, a classifier will be added on top of the encode, only use in supervised settings

loss:
  # If model is EncoderClassifier, use BCEWithLogitsLoss
  name: BCEWithLogitsLoss
  params:
    pos_weight: 1.0 # 1.0, cardinality_weight
    reduction: mean

optimizer:
  name: Adam
  params:
    lr: 0.001