
# System Parameters

## Verbosity level of the logs.
logging_level: INFO

# Seed for reproducibility.
seed: 42

## Used cached files to skip computations if available.
use_file_cache: False

## Use the last checkpoint to continue training
use_last_checkpoint: False

## If True, the training will be skipped if a checkpoint is found.

skip_training_if_checkpoint: False

# Evaluation Parameters

## Number of top-k predictions to be considered for evaluation.
k: [1, 5, 10]

# Alignment Parameters

alignment_params:
  ## Threshold to be used to filter predictions.
  ## If Null, final alignment will not be filtered by score.
  threshold: 0.7 # 0.7

  ## Cardinality to be used to filter predictions.
  ## If Null, final alignment will not be filtered by cardinality.
  ## Only used in full alignment tasks.
  cardinality: null # 1

matcha_params:
  ## JAVA Heap Size
  max_heap: 64G
  ## Filter to generate candidates for global alignment.
  threshold: 0.9 # 0.7, 0.8, 0.9
  ## Matchers ro be used to calculate the similarity between the candidates.
  matchers: [LM, BKM, SM, WM, LLM]
  # Cardinality of negatives in the training set
  negcardinality: 10 # 9, 99
  # Filter to generate negatives in the training set
  negthreshold: 0.1 #0.4, 0.5, 0.6
  # Samplers to be used to generate negatives in the training set
  samplers: 'all' # all, rand, diff
  # If matcha scores should be calculated. Serves to speed up the process if not needed. Warning: If False, the scores will not be available and can break the pipeline.
  calculate_scores: True

## Whether to plot the distribution of the similarities in the negative set.
plot_negatives:
  enabled: True
  figsize: [8, 5]
  kde: True
  bins: 20
  color: blue
  alpha: 0.6
  dpi: 300
  grid: True

dataset_params:
  ## Validation set to be used to stop training, and in training guidance.
  ## If Null or not declared, no validation set will be used.
  validation_set: 0.1
  
  ## Prompt Dataset Configs [Optional] Only used if model is prompt based
  ## Should should be list of params of size n (equal for all lists so that it can behabe like an array)
  ## If only one value is given, a single prompt will be used per source-target pair
  ## If n values are given, n prompts will be used per source-target pair and will be agregated following the agrgg param
  example: [True] # True, False
  positive_examples: [1] #1, 3, 5
  negative_examples: [1] #1, 3, 5
  task_context: [True] #
  separator: ['comma'] # comma, paranthesis
  comparison_type: ['Synonym'] # Synonym, Equivalent, Match
  label_cardinality: [1] #  3, 5, 100
  context_type : ['Parent'] # Parent, Child, Top
  context_cardinality: [1] # 3, 5, 100
  context_semantics: [part_of] # part_of, kind_of, type_of, subclass_of, with_subclass, with_part, with_type, with_kind
  likelihood: [float] # float, int, cat

training_params:
  epochs: 10 # 50
  batch_size: 1 # 1, 32
  num_workers: 0
  shuffle: True
  val_every: 1
  save_interval: 5
  ## Not used in for MLP models
  gradient_accumulation_steps: 1
  mixed_precision: True
  
stopper:
  name: StableLossStopping
  params:
    patience: 5 # 5, 10
    min_delta: 1e-4

# model:
#   name: MlpClassifier
#   params:
#     layers: [128, 256, 128]

model:
  name: PromptModel
  params:
    model_version: google/flan-t5-base # google/flan-t5-base/, meta-llama/Llama-3.3-70B-Instruct/, deepseek-ai/deepseek-llm-7b
    use_critic: True
    max_length: 50
    aggregation_strategy: 'mean' # mean, max, min
    use_lora: True
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.05

loss:
  name: BCEWeightedLoss
  params:
    pos_weight: 1.0 # 1.0, cardinality_weight
    reduction: mean

optimizer:
  name: Adam
  params:
    lr: 0.001